import type { Metadata } from "next";
// @ts-ignore: side-effect CSS import without module declarations
import "./styles/variables.css";
// @ts-ignore: side-effect CSS import without module declarations
import "./styles/reset.css";

export const metadata: Metadata = {
  title: "A component library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Geist:wght@100..900&display=swap');
        </style>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
