import type { Metadata } from "next";
// @ts-ignore: side-effect CSS import without module declarations
import "./styles/variables.css";
// @ts-ignore: side-effect CSS import without module declarations
import "./styles/reset.css";

export const metadata: Metadata = {
  title: "A component library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Geist:wght@100..900&display=swap');
        </style>
      </head>
      <body>
        <script
          id="theme-script"
          dangerouslySetInnerHTML={{
            __html: `
      (function () {
  try {
    const theme = localStorage.getItem("theme") || "system";
    const root = document.documentElement;

    if (theme === "system") {
      const isDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
      root.dataset.theme = isDark ? "dark" : "light";
    } else {
      root.dataset.theme = theme;
    }
  } catch {}
})();
    `,
          }}
        />
        {children}
      </body>
    </html>
  );
}
